<?php
/**
 * The only server-side code in this project. Keep it this size.
 *
 * Config lives OUTSIDE the document root. Its DB user holds INSERT on one
 * table and nothing else, so a leaked credential buys junk rows, not data.
 * See docs/DEPLOYMENT.md for the CREATE TABLE and GRANT.
 */
declare(strict_types=1);

/**
 * TWO CALLERS, TWO REPLIES.
 *
 * src/scripts/form.ts posts with `Accept: application/json`, reads the result,
 * fires generate_lead off it and then navigates to /thankyou/. It needs JSON.
 *
 * A NATIVE FORM POST DOES NOT SEND THAT HEADER, and it happens more often than
 * it looks: JavaScript disabled, the island failing to load, a bot, or a
 * browser that submitted before the bundle arrived. Those callers used to be
 * shown a page of raw JSON. They now get a 303 to /thankyou/ — the same
 * destination the island uses, so the conversion lands in the same place and
 * the goal counts both.
 */
$wantsJson = str_contains((string) ($_SERVER['HTTP_ACCEPT'] ?? ''), 'application/json');

/** Success, in whichever form the caller asked for. */
$done = function (array $payload) use ($wantsJson): never {
    if ($wantsJson) {
        header('Content-Type: application/json');
        exit(json_encode($payload));
    }
    /* 303, not 302: the browser must re-issue as GET, so a refresh on
       /thankyou/ cannot repost the form. */
    $form = isset($payload['form']) ? '?form=' . rawurlencode((string) $payload['form']) : '';
    header('Location: /thankyou/' . $form, true, 303);
    exit;
};

$fail = function (int $code, string $msg) use ($wantsJson): never {
    http_response_code($code);
    // Fixed strings only. User input is never echoed back.
    if ($wantsJson) {
        header('Content-Type: application/json');
        exit(json_encode(['ok' => false, 'error' => $msg]));
    }
    /* Deliberately NOT a redirect to /thankyou/: a failure that lands on the
       thank-you page would tell the visitor their message was sent when it was
       not, and would count a conversion that never happened. */
    header('Content-Type: text/plain; charset=utf-8');
    exit($msg);
};

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { $fail(405, 'Method not allowed.'); }

$cfg = require '/var/www/vhosts/roarsinc.com/private/contact-config.php';

// Honeypot: a field real people never see and never fill. Answered exactly
// like a success so a bot learns nothing from the difference.
if (($_POST['company_website'] ?? '') !== '') { $done(['ok' => true]); }

$ip = $_SERVER['REMOTE_ADDR'] ?? '0.0.0.0';

// Rate limit: one file per IP hash, N posts per window. Cheap, no extra service.
$bucket = sys_get_temp_dir() . '/rl_' . hash('sha256', $ip . $cfg['rate_salt']);
$hits = is_file($bucket) && filemtime($bucket) > time() - $cfg['rate_window']
    ? (int) file_get_contents($bucket) : 0;
if ($hits >= $cfg['rate_max']) { $fail(429, 'Too many submissions. Try again shortly.'); }
file_put_contents($bucket, (string) ($hits + 1), LOCK_EX);

// Turnstile, verified server-side. A token the browser never checks is theatre.
$verify = @file_get_contents(
    'https://challenges.cloudflare.com/turnstile/v0/siteverify',
    false,
    stream_context_create(['http' => [
        'method' => 'POST', 'timeout' => 10, 'ignore_errors' => true,
        'header' => 'Content-Type: application/x-www-form-urlencoded',
        'content' => http_build_query([
            'secret' => $cfg['turnstile_secret'],
            'response' => (string) ($_POST['cf-turnstile-response'] ?? ''),
            'remoteip' => $ip,
        ]),
    ]]),
);
if (!$verify || !(json_decode($verify, true)['success'] ?? false)) { $fail(403, 'Verification failed.'); }

$form  = in_array($_POST['form'] ?? '', ['contact', 'newsletter', 'guide', 'callback'], true)
    ? $_POST['form'] : $fail(422, 'Unknown form.');
$name  = trim((string) ($_POST['name'] ?? ''));
$email = filter_var(trim((string) ($_POST['email'] ?? '')), FILTER_VALIDATE_EMAIL);
if ($email === false) { $fail(422, 'A valid email is required.'); }
// The guide form asks for a first name but does not insist on one: the export
// stars only the email, and a template is not worth losing a lead over.
if ($form !== 'guide' && $name === '') { $fail(422, 'Name and a valid email are required.'); }

/**
 * THE GUIDE ALLOWLIST.
 *
 * The browser posts a SLUG, never a path, and a slug that is not a key in this
 * file is refused before it touches the filesystem. That is the whole defence
 * against path traversal: there is no string from the request in the filename.
 *
 * guides.php is GENERATED by scripts/build-email-manifest.mjs from
 * src/content/resources/*.md, which is also where the guide pages come from, so
 * the allowlist cannot drift from the pages the way a second hand-kept list
 * did. It carries the title, shelf, page count, summary and section headings
 * the download email prints.
 */
$GUIDES = require __DIR__ . '/guides.php';

$guide = null;
if ($form === 'guide') {
    $slug = (string) ($_POST['guide'] ?? '');
    if (!isset($GUIDES[$slug])) { $fail(422, 'Unknown guide.'); }
    $meta = $GUIDES[$slug];
    $path = rtrim($cfg['tools_dir'], '/') . '/' . $meta['file'];
    // Belt and braces. The filename came from the manifest, not the request, so
    // realpath can only fail here if the file is missing or the directory moved.
    $real = realpath($path);
    $root = realpath($cfg['tools_dir']);
    if ($real !== false && $root !== false && str_starts_with($real, $root . '/')
        && is_file($real) && filesize($real) <= $cfg['max_attach']) {
        $guide = ['path' => $real, 'name' => $meta['file'], 'size' => filesize($real)] + $meta;
    } else {
        // A missing file is NOT an error to the visitor. The row is still saved
        // and sales still gets the notification, so the lead is not lost; the
        // email links the PDF instead of carrying it.
        $guide = ['path' => null, 'name' => $meta['file'], 'size' => 0] + $meta;
    }
}

// Prepared statement. No value is ever concatenated into SQL.
$pdo = new PDO($cfg['dsn'], $cfg['db_user'], $cfg['db_pass'], [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_EMULATE_PREPARES => false,
]);
$phone   = mb_substr(trim((string) ($_POST['phone'] ?? '')), 0, 40);
$message = mb_substr(trim((string) ($_POST['message'] ?? '')), 0, 5000);
$pdo->prepare(
    'INSERT INTO submissions (form, name, email, phone, message, page_url, referrer, ip, user_agent)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'
)->execute([
    $form, mb_substr($name, 0, 190), $email, $phone, $message,
    mb_substr((string) ($_POST['page_url'] ?? ''), 0, 500),
    mb_substr((string) ($_SERVER['HTTP_REFERER'] ?? ''), 0, 500),
    $ip, mb_substr((string) ($_SERVER['HTTP_USER_AGENT'] ?? ''), 0, 255),
]);

/* The row's own id, printed in the email as INQUIRY RS-000123 and put in the
   notification's subject. A real handle both sides can quote, rather than a
   random string that matches nothing. */
$refId = 'RS-' . str_pad((string) $pdo->lastInsertId(), 6, '0', STR_PAD_LEFT);

/**
 * THE TEMPLATE RENDERER. Two forms, and deliberately no more than two:
 *
 *   {{key}}                a value. ESCAPED HERE, at substitution, so there is
 *                          no path by which a visitor's name or message can
 *                          put markup into an email that someone else opens.
 *   {{#key}}...{{/key}}    kept when the value is non-empty, dropped when it
 *                          is not. That is what stops a blank Phone row or an
 *                          empty Brief row printing as a labelled void.
 *
 * Sections run first so an empty one takes its own {{placeholders}} with it.
 */
$render = function (string $file, array $vars): string {
    $tpl = (string) @file_get_contents(__DIR__ . '/' . $file);
    if ($tpl === '') { return ''; }
    $tpl = preg_replace_callback(
        '/\{\{#([a-z0-9_]+)\}\}(.*?)\{\{\/\1\}\}/s',
        static fn(array $m): string => ($vars[$m[1]] ?? '') === '' ? '' : $m[2],
        $tpl,
    ) ?? $tpl;
    return preg_replace_callback(
        '/\{\{([a-z0-9_]+)\}\}/',
        static fn(array $m): string => htmlspecialchars((string) ($vars[$m[1]] ?? ''), ENT_QUOTES, 'UTF-8'),
        $tpl,
    ) ?? $tpl;
};

/**
 * One HTML email, with a plain-text alternative and an optional attachment.
 *
 * multipart/alternative inside multipart/mixed is the nesting every client
 * expects: the text and HTML are two versions of the same message, and the PDF
 * is a third thing alongside both. Flattening it makes Outlook show the plain
 * text as a second attachment.
 *
 * Built by hand because this project ships no mail library and is not adding
 * one for three parts. Each boundary is random per message, so nothing in a
 * body can close its own part early. Base64 in 76-character lines, which is
 * what RFC 2045 asks for. The subject is encoded because these carry em dashes.
 */
$send = function (string $to, string $subject, string $html, string $text, ?array $attach = null) use ($cfg): void {
    $alt = '=_a' . bin2hex(random_bytes(12));
    $inner = "--{$alt}\r\n"
        . "Content-Type: text/plain; charset=UTF-8\r\n"
        . "Content-Transfer-Encoding: base64\r\n\r\n"
        . chunk_split(base64_encode($text), 76, "\r\n")
        . "--{$alt}\r\n"
        . "Content-Type: text/html; charset=UTF-8\r\n"
        . "Content-Transfer-Encoding: base64\r\n\r\n"
        . chunk_split(base64_encode($html), 76, "\r\n")
        . "--{$alt}--\r\n";

    $subj = '=?UTF-8?B?' . base64_encode($subject) . '?=';
    $head = "From: {$cfg['from']}\r\nMIME-Version: 1.0\r\n";

    if ($attach === null) {
        @mail($to, $subj, $inner, $head . "Content-Type: multipart/alternative; boundary=\"{$alt}\"");
        return;
    }
    $mix = '=_m' . bin2hex(random_bytes(12));
    $body = "--{$mix}\r\n"
        . "Content-Type: multipart/alternative; boundary=\"{$alt}\"\r\n\r\n"
        . $inner
        . "--{$mix}\r\n"
        . "Content-Type: application/pdf; name=\"{$attach['name']}\"\r\n"
        . "Content-Transfer-Encoding: base64\r\n"
        . "Content-Disposition: attachment; filename=\"{$attach['name']}\"\r\n\r\n"
        . chunk_split(base64_encode((string) file_get_contents($attach['path'])), 76, "\r\n")
        . "--{$mix}--";
    @mail($to, $subj, $body, $head . "Content-Type: multipart/mixed; boundary=\"{$mix}\"");
};

// Headers carry only the validated address — $email has been through
// FILTER_VALIDATE_EMAIL, so it cannot carry a CRLF and cannot inject a header.
// $name never goes in a header at all, only in a body.
$who   = $name !== '' ? $name : 'there';
$first = $name !== '' ? explode(' ', $name)[0] : 'there';
$site  = rtrim((string) ($cfg['site_url'] ?? 'https://www.roarsinc.com'), '/');
// The registered office, from src/lib/site.ts. One line, because the email
// footer is one line; the other four offices are on /contact-us/.
$postal = (string) ($cfg['postal_address'] ?? '4th Block, Jaynagar, Bengaluru, India 560041');

// Sales first, and in plain text: it is a work notification, not a brand piece.
@mail(
    $cfg['notify_to'],
    "Roars enquiry {$refId}: {$form}",
    "From: {$name} <{$email}>\r\nPhone: {$phone}\r\n\r\n{$message}",
    "From: {$cfg['from']}\r\nReply-To: {$email}",
);

if ($guide !== null) {
    $url = "{$site}/tools/" . rawurlencode($guide['name']);
    $html = $render('email-guide.html', [
        'first_name'        => $first,
        'resource_title'    => $guide['title'],
        'resource_category' => $guide['category'],
        'issued_at'         => gmdate('j M Y'),
        'page_count'        => $guide['pages'],
        // Only when the file was actually found and is under max_attach.
        'file_size'         => $guide['size'] > 0 ? round($guide['size'] / 1024) . ' KB' : '',
        'download_url'      => $url,
        'chapter_1'         => $guide['chapters'][0] ?? '',
        'chapter_2'         => $guide['chapters'][1] ?? '',
        'chapter_3'         => $guide['chapters'][2] ?? '',
        'postal_address'    => $postal,
    ]);
    $text = "Hi {$first},\r\n\r\nYour copy of {$guide['title']} is "
        . ($guide['path'] !== null ? "attached, and also here:\r\n{$url}" : "here:\r\n{$url}")
        . "\r\n\r\nIt is one page — print it, fill it in, take it into the room. "
        . "If the problem turns out to be bigger than a page, reply to this email "
        . "and we will take a look.\r\n\r\n— Roars Technologies\r\n{$postal}\r\n";
    $send(
        $email,
        "Your copy of {$guide['title']}",
        $html,
        $text,
        $guide['path'] !== null ? ['path' => $guide['path'], 'name' => $guide['name']] : null,
    );
} else {
    $labels = ['contact' => 'Contact form', 'newsletter' => 'Newsletter', 'callback' => 'Callback request'];
    $html = $render('email-inquiry.html', [
        'first_name'     => $first,
        'full_name'      => $who,
        'email'          => $email,
        'phone'          => $phone,
        'form_label'     => $labels[$form] ?? $form,
        'message'        => $message,
        'ref_id'         => $refId,
        'submitted_at'   => gmdate('j M Y, H:i') . ' UTC',
        'postal_address' => $postal,
    ]);
    $text = "Hi {$first},\r\n\r\nYour inquiry is logged as {$refId} and sitting with "
        . "our team. A strategist reads it and writes back inside one business day.\r\n\r\n"
        . "On record:\r\n  Name: {$who}\r\n" . ($phone !== '' ? "  Phone: {$phone}\r\n" : '')
        . "  Reply to: {$email}\r\n" . ($message !== '' ? "  Brief: {$message}\r\n" : '')
        . "\r\nSomething wrong above? Reply to this email and correct it — it reaches "
        . "the same person.\r\n\r\n— Roars Technologies\r\n{$postal}\r\n";
    $send($email, "Logged, {$first} — reply within 24 hours", $html, $text);
}

// generate_lead fires from THIS response, never from the submit handler.
// Clicking is not converting.
$done(['ok' => true, 'event' => 'generate_lead', 'form' => $form]);
