<?php
/**
 * GENERATED by scripts/build-email-manifest.mjs. Do not edit.
 *
 * Every gated guide, described once, from src/content/resources/*.md. This is
 * also contact.php's allowlist: a slug absent from these keys is refused before
 * anything touches the filesystem, so no string from a request ever reaches a
 * filename.
 */
declare(strict_types=1);

return [
    'building-partnerships' => [
        'title' => 'Building Partnerships',
        'file' => 'building-partnerships.pdf',
        'category' => 'BUSINESS MODEL',
        'pages' => '1',
        'summary' => 'Many complex problems have several different yet related causes and effects. With many organisations having limited resources, forming partnerships is a good approach to not only increase capability but also your reach.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'business-model-canvas' => [
        'title' => 'Business Model Canvas',
        'file' => 'Business-Model-canvas.pdf',
        'category' => 'BUSINESS MODEL',
        'pages' => '1',
        'summary' => 'The Business Model Canvas is a one page overview that lays out both what you do (or want to do), and how you go about doing it ; enabling structured conversations around management and strategy.',
        'chapters' => ['What is this for?', 'Step-by-step guide.'],
    ],
    'business-plan' => [
        'title' => 'Business Plan',
        'file' => 'Business-plans.pdf',
        'category' => 'BUSINESS MODEL',
        'pages' => '1',
        'summary' => 'A structured description of how you do what you do. The plan needs to articulate the problem the business proposes to solve, a vision for how that will be accomplished.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'evidence-planning' => [
        'title' => 'Evidence Planning',
        'file' => 'Evidence-Planning.pdf',
        'category' => 'STRATEGY',
        'pages' => '1',
        'summary' => 'The Evidence Planning tool is a quick way to help articulate and improve what you are trying to accomplish. It gives you an easy way to define and share what it is that you’re trying to do.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'innovation-flowchart' => [
        'title' => 'Innovation Flowchart',
        'file' => 'Innovation-Flowchart.pdf',
        'category' => 'STRATEGY',
        'pages' => '1',
        'summary' => 'The Innovation Flowchart gives a detailed overview of the various stages in an innovation process, listing the activities, requirements and goals of each stage.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'learning-loop' => [
        'title' => 'Learning Loop',
        'file' => 'Learning-loop.pdf',
        'category' => 'OUR FAVOURITE',
        'pages' => '1',
        'summary' => 'The Learning Loop is a tool that helps you to define how the work you do now informs what you do next. It provides a high-level perspective on how implementing social change can be broken down into iterative cycles.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'people-connection-map' => [
        'title' => 'People & Connection Map',
        'file' => 'People-connection.pdf',
        'category' => 'STRATEGY',
        'pages' => '1',
        'summary' => 'The People and Connections Map is a quick and simple way to visualise exactly who you are trying to reach and how.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'pitching-checklist' => [
        'title' => 'Pitching Checklist',
        'file' => 'Pitching-Checklist.pdf',
        'category' => 'PITCHING',
        'pages' => '1',
        'summary' => 'If you want to sell a killer business idea, your pitch needs to pack a punch. This 5-part checklist is the best way to make sure your pitch hits home.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'problem-definition' => [
        'title' => 'Problem Definition',
        'file' => 'Problem-Definition.pdf',
        'category' => 'PITCHING',
        'pages' => '1',
        'summary' => 'Problem Definition is a deceptively simple task. What at first seems to be the problem is often merely a symptom of a deeper problem. This tool works to both open a problem up, presenting it in a way that can be examined from a number of angles.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'product-solution-benefit' => [
        'title' => 'Product Solution Benefit',
        'file' => 'Product-solution-benefit.pdf',
        'category' => 'PROBLEM DISCOVERY',
        'pages' => '1',
        'summary' => 'Storyboarding to help find out customer pain points and find a magical solutions for there problems.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'prototype-testing-plan' => [
        'title' => 'Prototype Testing Plan',
        'file' => 'Prototype-Testing-plan.pdf',
        'category' => 'PROBLEM DISCOVERY',
        'pages' => '1',
        'summary' => 'IDEA: TRY: TEST: SPECIFY. Prototyping is more than just ‘trying out’; it is a structured way to check that you have an efficient and fitting solution.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'swot-analysis' => [
        'title' => 'SWOT Analysis',
        'file' => 'SWOT-analysis.pdf',
        'category' => 'OUR FAVOURITE',
        'pages' => '1',
        'summary' => 'SWOT stands for Strengths, Weaknesses, Opportunities and Threats. A SWOT analysis can be carried out for a specific project, organisation or even a whole sector.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'target-group' => [
        'title' => 'Target Group',
        'file' => 'target-group.pdf',
        'category' => 'PROBLEM DISCOVERY',
        'pages' => '1',
        'summary' => 'Target Group is probably best used when you are trying to work out some initial ideas about who you want to cater to, and why.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'value-proposition' => [
        'title' => 'Value Proposition',
        'file' => 'Value-proposition.pdf',
        'category' => 'PROBLEM DISCOVERY',
        'pages' => '1',
        'summary' => 'Identify your customer’s major jobs to be done, the pains they face when trying to accomplish their jobs and the gains they perceive by getting their jobs done.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
    'website-redesign-roi-calculator' => [
        'title' => 'Web Redesign ROI Calculator',
        'file' => 'website-redesign-roi-calculator.pdf',
        'category' => 'STRATEGY',
        'pages' => '1',
        'summary' => 'ROI Calculator can be helpful in finding out how much a lean web design can be helpful for you.',
        'chapters' => ['What is this for?', 'Step-by-step guide.', 'Where it goes wrong.'],
    ],
];
